### ISSUE TITLE
Would you mind adding a license to this repo?

### ISSUE THREAD

**Issue by JanNash** [shanealynn/async_flask#10]
Hi, I'd love to use and adapt some of your code for a personal project.  
In [the post on your website](https://www.shanelynn.ie/asynchronous-updates-to-a-webpage-with-flask-and-socket-io/), you say

> You can find all of the source code on GitHub, with instructions on how to install the necessary libraries etc. Feel free to adapt to your own needs, and leave any comments if you come up with something neat or have any problems.

However, I'd feel much more comfortable using and adapting if there was an actual license file in the repo (e.g. BSD-3-Clause but ultimately, it's your choice :)).

**Comment by shanealynn** [comment]
No problem. Done.

**Comment by JanNash** [comment]
Awesome, thanks :)
