### ISSUE TITLE
example doesn t work

### ISSUE THREAD

**Issue by laticoda** [shanealynn/async_flask#11]
Hi, could you please give update , i am on python 3.7.3 with flaskio and gevent, it works on terminal side but nothing appears on the page ; could you also improve to keep only the last updated value (not the entire list).
thanks !

**Comment by hugoib** [comment]
Yes... It's broken :(

**Comment by Shane-EdgeTier** [comment]
Updated now for python 3.9. (slightly delayed eh!?)
