### ISSUE TITLE
get incoming request

### ISSUE THREAD

**Issue by Elappnano** [shanealynn/async_flask#14]
hello
how to get incoming request in replace of random number. I use `number= request.values.get('test')` but the host shows nothing.

**Comment by Shane-EdgeTier** [comment]
Is this on the frontend? You'll need to look at the application.js to catch the numbers there:

<img width="695" alt="image" src="https://user-images.githubusercontent.com/87317534/162640110-4690dbfd-2dcd-4500-8da8-6022ab4cf9dc.png">
