### ISSUE TITLE
 unsupported version of the Socket.IO

### ISSUE THREAD

**Issue by iHaagcom** [shanealynn/async_flask#16]
Installed package with the following command: pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org Flask-SocketIO==3.1.2

Error when launching the website shows the below information:

The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)
The client is using an unsupported version of the Socket.IO or Engine.IO protocols

The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)
The client is using an unsupported version of the Socket.IO or Engine.IO protocols
The client is using an unsupported version of the Socket.IO or Engine.IO protocols

**Comment by kevin-soutar** [comment]
I am getting this error as well, any ideas?

**Comment by Shane-EdgeTier** [comment]
Hey, I can take a look, sounds like this project may need an overall requirements.txt upgrade with lots of versions. I'll see if i can get it working on a newer version of Python.

**Comment by kevin-soutar** [comment]
I think I that unfortunately the web socket code has been updated and deprecated a bunch of code in the project. The error comes back from the browser, when it calls to check in.  That would be really great if you could take a look, thx

**Comment by Shane-EdgeTier** [comment]
Updated socketio version now - to 4.4.1, and tested on Python3.9 with upgrade requirements.txt
