### ISSUE TITLE
Python 3.5 version

### ISSUE THREAD

**Issue by kf106** [shanealynn/async_flask#3]
Is there any chance you could release a python 3.5 version of this? gevent-websocket now supports 3.5...

**Comment by shanealynn** [comment]
Hi Keir,

Yes, that's a good idea - I'll have a look at updating the code, but time
is in short supply.

If you have any luck in getting it working in the meantime, please let me
know and I'll integrate your code!

Thanks,

Shane

On Sat, Sep 30, 2017 at 9:50 PM, Keir Finlow-Bates <notifications@github.com

**Comment by kf106** [comment]
In the end I canabalized Miguel's Flask-SocketIO example. You can see the result here: https://github.com/Chainfrog-dev/async_flask_2 
It does the same as your example.

**Comment by shanealynn** [comment]
Ah great, good work.

I'll have a look at updating my post ASAP.

On Sun, Oct 1, 2017 at 12:32 PM, Keir Finlow-Bates <notifications@github.com

**Comment by bholagabbar** [comment]
@kf106 Thanks a ton, works beautifully.

**Comment by Radar-Lei** [comment]
@kf106 @shanealynn  Thanks for your great work, it really inspires me.

**Comment by shanealynn** [comment]
Working in Python 3.6 now!
