### ISSUE TITLE
Not working on Chrome?

### ISSUE THREAD

**Issue by allback122** [shanealynn/async_flask#6]
I just tried to run application.py. While on Firefox and Edge the page is updated with the numbers normally, on Chrome nothing will load below "Numbers List". How can i solve that?

**Comment by safeisnotanoption** [comment]
Same problem here

**Comment by sudojobs** [comment]
same problem

**Comment by shanealynn** [comment]
Hey, will have a look and see if I can get this working - was there any error or message in your browser console?

**Comment by shanealynn** [comment]
Have now updated flask-socketio library in the requirements.txt and working in Chrome ok I think.
