### ISSUE TITLE
Only the first random generated number is shown, very slow to show new numbers

### ISSUE THREAD

**Issue by JoooostB** [shanealynn/async_flask#8]
After a start, the first random generated number is shown instantly. However, subsequent numbers take ages to be displayed on the page. Any ideas?

```
Click==7.0
Flask==1.0.2
Flask-SocketIO==3.1.2
gevent==1.4.0
greenlet==0.4.15
itsdangerous==1.1.0
Jinja2==2.10
MarkupSafe==1.1.0
python-engineio==3.2.3
python-socketio==3.1.1
six==1.12.0
Werkzeug==0.14.1

**Comment by thirdeye-peter** [comment]
I had the same problem. For some reason I had to use 

```
socketio = SocketIO(app, async_mode="threading")
```

Even though I installed eventlet and ran flask with gunicorn.

**Comment by fengwang** [comment]
> I had the same problem. For some reason I had to use
> 
> ```
> socketio = SocketIO(app, async_mode="threading")
> ```
> 
> Even though I installed eventlet and ran flask with gunicorn.

Works for me. Maybe it is even better to submit a patch?

**Comment by markqiu** [comment]
I think, it's problem of eventlet. If I uninstall eventlet or use async_mode="threading", then it works, even did not use thread.

`from flask import Flask
from flask_socketio import SocketIO, emit
from time import sleep


app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
SOCKET_CONFIG = {
    "engineio_logger": True,
    "logger": True,
    "async_mode": "threading"
}
socketio = SocketIO(app, **SOCKET_CONFIG)


@socketio.on('aaa')
def test_connect():
    print("Welcome, aaa received")
    for i in range(1,1000):
        emit('aaa_response', {'data': f'Server{i}'})
        sleep(1)


if __name__ == '__main__':
    socketio.run(app, port=8000)
`

**Comment by markqiu** [comment]
I worked it out. 
Just like the following:
`from flask import Flask
from flask_socketio import SocketIO, emit


app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)
thread = None


def backtest(start, end):
    print("Welcome, aaa backtest")
    for i in range(start, end):
        socketio.emit('backtest_response', {'data': f'Server{i}'})


@socketio.on('backtest')
def on_backtest(init_data):
    global thread
    if thread is None:
        thread = socketio.start_background_task(backtest, 1, 1000)


if __name__ == '__main__':
    socketio.run(app, port=8000)`

ref: https://github.com/miguelgrinberg/python-socketio/tree/master/examples/server/wsgi
